### ISSUE TITLE
Cannot use custom path

### ISSUE THREAD

**Issue by wgj** [jenkinsci/prometheus-plugin#135]
https://issues.jenkins-ci.org/browse/JENKINS-59991

### Steps to reproduce
Using a custom path for Prometheus metrics collection recieves a 404.

Please see screenshots.

STR change Prometheus Path on Jenkins configuration page. Navigate to path and observe 404.

Prometheus defined:
<img width="1332" alt="Prometheus defined" src="https://user-images.githubusercontent.com/463564/67898942-e755ce00-fb26-11e9-8077-585e5d107a22.png">

Prometheus working:
<img width="1332" alt="Prometheus working" src="https://user-images.githubusercontent.com/463564/67898941-e755ce00-fb26-11e9-9e2a-cab78798844f.png">

Metrics defined:
<img width="1332" alt="Metrics defined" src="https://user-images.githubusercontent.com/463564/67899045-1b30f380-fb27-11e9-978c-2812ea0fa67a.png">

Metrics 404:
<img width="1332" alt="Metrics 404" src="https://user-images.githubusercontent.com/463564/67898943-e755ce00-fb26-11e9-9ada-966fadae31b7.png">

### Expected behaviour
The defined path should return Prometheus metrics.

### Actual behaviour
The defined path returns a 404.

### Server configuration

**Operating system**: Using Docker Hub image jenkins/jenkins:lts deployed with Helm chart stable/jenkins 

**Jenkins Version**: 2.190.2

**Plugin Version**: 2.0.6

### Notify

@markyjackson-taulia

**Comment by jimenezfd** [comment]
I have the same issue with the Prometheus metrics plugin (V. 2.0.6) . It was installed in tradicional server like a service. In the first time, the plugin worked perfectly but when I restarted the Jenkins service the plugin doesn't work and the url return:

**HTTP ERROR 404
Problem accessing /prometheus/. Reason:

    Not Found
Powered by Jetty:// 9.4.z-SNAPSHOT**

Anybody have idea about this issue?

**Comment by jlambrechts** [comment]
I have to access the metrics from the prometheus plugin from

/jenkins/prometheus

I was having the same problem when trying /prometheus/

**Comment by jimenezfd** [comment]
I found a few stuff that I changed on the config archive of prometheus (xml) and finally works to me:

<?xml version='1.1' encoding='UTF-8'?>
<org.jenkinsci.plugins.prometheus.config.PrometheusConfiguration plugin="prometheus@2.0.6">
  <urlName>prometheus</urlName>
  <additionalPath></additionalPath>
  <defaultNamespace>default</defaultNamespace>
  <jobAttributeName>jenkins_job</jobAttributeName>
  <useAuthenticatedEndpoint>false</useAuthenticatedEndpoint>
  <collectingMetricsPeriodInSeconds>120</collectingMetricsPeriodInSeconds>
  <countSuccessfulBuilds>true</countSuccessfulBuilds>
  <countUnstableBuilds>true</countUnstableBuilds>
  <countFailedBuilds>true</countFailedBuilds>
  <countNotBuiltBuilds>true</countNotBuiltBuilds>
  <countAbortedBuilds>true</countAbortedBuilds>
  <fetchTestResults>true</fetchTestResults>
  <processingDisabledBuilds>false</processingDisabledBuilds>
</org.jenkinsci.plugins.prometheus.config.PrometheusConfiguration>

Get back to original values that plugin brought on first time. I found this archive on Jenkins_home.
 
I hope what this help you.

**Comment by Mr-TiNTaMaR** [comment]
Hello,

I faced the same problem. I resolved it by using the [Jenkins Configuration as Code Plugin](https://jenkins.io/projects/jcasc/) with this config file (prometheus.yml) : 
```
unclassified:  
  prometheusConfiguration:
    collectingMetricsPeriodInSeconds: 120
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    processingDisabledBuilds: false  
    useAuthenticatedEndpoint: false
```

I also delete the original config file `org.jenkinsci.plugins.prometheus.config.PrometheusConfiguration.xml`  and then restart Jenkins (apply the new config in Manage Jenkins > Configuration as Code)

Hope this help.
