### ISSUE TITLE
get 1 from default_jenkins_builds_last_build_result during job building

### ISSUE THREAD

**Issue by nieyong1** [jenkinsci/prometheus-plugin#155]
my plugin version is 2.06. I have one job never succeed. But I get 1 from default_jenkins_builds_last_build_result during job building.

**Comment by viveksiddineni** [comment]
> my plugin version is 2.06. I have one job never succeed. But I get 1 from default_jenkins_builds_last_build_result during job building.

+1

**Comment by markyjackson-taulia** [comment]
This is a scrape config. issue

**Comment by viveksiddineni** [comment]
@markyjackson-taulia , could you please post on how to get the scrape config.json issue fixed and get authentic default_jenkins_builds_last_build_result values instead of 1 always ? Thanks in advance .

**Comment by viveksiddineni** [comment]
@markyjackson-taulia  prometheus-values.yml looks like the below: 


`alertmanager:
  enabled: true
  persistentVolume:
    storageClass: gp2
    size: 100Gi
server:
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations: 
       kubernetes.io/ingress.class: nginx
       kubernetes.io/tls-acme: 'true'
    hosts:
       - prometheus.xxx.xxx.xxx
  persistentVolume:
    storageClass: gp2
    size: 200Gi
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      - job_name: 'jenkins'
        metrics_path: '/prometheus/'
        scheme: https
        static_configs:
        - targets: ['jenkins.xxx.xxx:443']
      - job_name: blackbox
        metrics_path: /probe
        params:
          module: [http_2xx]
        static_configs:
          - targets:
            - https://about.google.xx              
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: xxxxxxx`

**Comment by viveksiddineni** [comment]
![Screen Shot 2020-10-21 at 11 39 30 AM (3)](https://user-images.githubusercontent.com/64419981/96743679-3fb65900-1392-11eb-85bb-037e9fe3c372.png)

**Comment by viveksiddineni** [comment]
```
--- 
alertmanager: 
  enabled: true
  persistentVolume: 
    size: 100Gi
    storageClass: gp2
server: 
  ingress: 
    annotations: 
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts: 
      - prometheus.n3c.ncats.io
  persistentVolume: 
    size: 200Gi
    storageClass: gp2
  service: 
    type: NodePort
serverFiles: 
  prometheus.yml: 
    scrape_configs: 
      - 
        job_name: prometheus
        static_configs: 
          - 
            targets: 
              - "localhost:9090"
      - 
        job_name: jenkins
        metrics_path: /prometheus/
        scheme: https
        static_configs: 
          - 
            targets: 
              - "jenkins.xxx.xx:443"
      - 
        job_name: blackbox
        metrics_path: /probe
        params: 
          module: 
            - http_2xx
        relabel_configs: 
          - 
            source_labels: 
              - __address__
            target_label: __param_target
          - 
            source_labels: 
              - __param_target
            target_label: instance
          - 
            replacement: "xxxxx:9115"
            target_label: __address__
        static_configs: 
          - 
            targets: 
              - "https://jenkins.xxxxx.io/"


```
