### ISSUE TITLE
get 1 from default_jenkins_builds_last_build_result during job building #155

### ISSUE THREAD

**Issue by viveksiddineni** [jenkinsci/prometheus-plugin#187]
### Steps to reproduce
How can we reproduce the issue

my plugin version is 2.06. I have one job never succeed. But I get 1 from default_jenkins_builds_last_build_result during job building.
### Expected behaviour
Show the actual build result instead of 1 always . Same default values for other fields instead of authentic values.

### Actual behaviour
@markyjackson-taulia , could you please post on how to get the scrape config.json issue fixed and get authentic default_jenkins_builds_last_build_result values instead of 1 always ? Thanks in advance .

### Server configuration

**Operating system**:

**Jenkins Version**:

**Plugin Version**:

Jenkins version 2.190.2
2.0.6 prometheus metrics plugin version

### Notify

@markyjackson-taulia
@nieyong1

**Comment by markyjackson-taulia** [comment]
The issue template has not been filled out

**Comment by viveksiddineni** [comment]
Steps to reproduce
How can we reproduce the issue

my plugin version is 2.06. I have one job never succeed. But I get 1 from default_jenkins_builds_last_build_result during job building.

Expected behaviour
Show the actual build result instead of 1 always . Same default values for other fields instead of authentic values.

Actual behaviour
@markyjackson-taulia , could you please post on how to get the scrape config.json issue fixed and get authentic default_jenkins_builds_last_build_result values instead of 1 always ? Thanks in advance .

Server configuration
Operating system:

Jenkins Version:

Plugin Version:

Jenkins version 2.190.2
2.0.6 prometheus metrics plugin version

Notify
@markyjackson-taulia
@nieyong1

**Comment by viveksiddineni** [comment]
alertmanager:
enabled: true
persistentVolume:
storageClass: gp2
size: 100Gi
server:
service:
type: NodePort
ingress:
enabled: true
annotations:
kubernetes.io/ingress.class: nginx
kubernetes.io/tls-acme: 'true'
hosts:
- prometheus.xxx.xxx.xxx
persistentVolume:
storageClass: gp2
size: 200Gi
serverFiles:
prometheus.yml:
scrape_configs:
- job_name: prometheus
static_configs:
- targets:
- localhost:9090
- job_name: 'jenkins'
metrics_path: '/prometheus/'
scheme: https
static_configs:
- targets: ['jenkins.xxx.xxx:443']
- job_name: blackbox
metrics_path: /probe
params:
module: [http_2xx]
static_configs:
- targets:
- https://about.google.xx
relabel_configs:
- source_labels: [address]
target_label: __param_target
- source_labels: [__param_target]
target_label: instance
- target_label: address
replacement: xxxxxxx

**Comment by markyjackson-taulia** [comment]
Thank you!

**Comment by viveksiddineni** [comment]
![Screen Shot 2020-10-21 at 11 39 30 AM (3)](https://user-images.githubusercontent.com/64419981/96743776-578ddd00-1392-11eb-8dbc-e704f964fa60.png)

**Comment by viveksiddineni** [comment]
```
--- 
alertmanager: 
  enabled: true
  persistentVolume: 
    size: 100Gi
    storageClass: gp2
server: 
  ingress: 
    annotations: 
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts: 
      - prometheus.n3c.ncats.io
  persistentVolume: 
    size: 200Gi
    storageClass: gp2
  service: 
    type: NodePort
serverFiles: 
  prometheus.yml: 
    scrape_configs: 
      - 
        job_name: prometheus
        static_configs: 
          - 
            targets: 
              - "localhost:9090"
      - 
        job_name: jenkins
        metrics_path: /prometheus/
        scheme: https
        static_configs: 
          - 
            targets: 
              - "jenkins.ctsa.io:443"
      - 
        job_name: blackbox
        metrics_path: /probe
        params: 
          module: 
            - http_2xx
        relabel_configs: 
          - 
            source_labels: 
              - __address__
            target_label: __param_target
          - 
            source_labels: 
              - __param_target
            target_label: instance
          - 
            replacement: "15.0.3.219:9115"
            target_label: __address__
        static_configs: 
          - 
            targets: 
              - "https://jenkins.ctsa.io/"
              - "https://monitor.n3c.ncats.io/"
              - "http://lparse.n3c.ncats.io:3100/loki/api/v1/labels"
              - "https://prometheus.n3c.ncats.io/"
              - "https://about.google"

```
