### ISSUE TITLE
Prometheus plugin endpoint showing blank page

### ISSUE THREAD

**Issue by mohanss08** [jenkinsci/prometheus-plugin#208]
Below is my jenkins environment.

```
Jenkins - 2.263.1(LTS) deployed through tomcat.
Prometheus metrics plugin - 2.0.8 
```

`http://jenkins-server/jenkins/prometheus` just shows the blank page on my browsers.

My prometheus.yml

```
  - job_name: 'jenkins'
    metrics_path: '/jenkins/prometheus'
    scheme: http
    static_configs:
    - targets: ['jenkins-server:80']
```
Even tried with authentication, however still blank page shown.

```
basic_auth:
  username: domain-user
  password: 98qw37asdkdsjfeiq1dedsewe
```

Jenkins `system log` section below message shown.

```
A thread (prometheus_async_worker thread/77119) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NullPointerException
```
Refered this issue - `https://github.com/jenkinsci/prometheus-plugin/issues/82` however it is closed, can't find the workaround in that.
