### ISSUE TITLE
Authentication documentation

### ISSUE THREAD

**Issue by danpalmer** [jenkinsci/prometheus-plugin#23]
I'd like to have the metrics authenticated, but I'm struggling to get it working. We use Google OAuth for our authentication with Jenkins, so there isn't an obvious username/password that we can use with basic auth. I've attempted to use the Jenkins API token for my account instead, but that has not worked.

Some documentation as to how to do this would be much appreciated!

**Comment by slamont** [comment]
Hi, I have exactly the same problem.
Our Jenkins instance is behind an nginx reverse proxy. I tried creating a 'location' for /prometheus that would be secured by a basic authentication and could not figure a way to make this work.

Documentation would be indeed much appreciated! :)

**Comment by aghassabian** [comment]
I have same situation as yours. Jenkins behind the reverse proxy and OAuth configured. I added the following configs to prometheus.yaml and could get the metrics on prometheus successfully:

```
  - job_name: 'jenkins'
    basic_auth:
      username: "username(OAuth username)"
      password: "Token of the user on jenkins"
    metrics_path: /prometheus
    scheme: https (if needed)
    static_configs:
      - targets: ['your jenkins address']
```
