### ISSUE TITLE
How to scrape Jenkins metrics inside Prometheus/Grafan using "metrics-access-key" ? Where to configure the key in Values.yaml?

### ISSUE THREAD

**Issue by kishorkk91** [jenkinsci/prometheus-plugin#251]
I have deployed this helm chart: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#kube-prometheus-stack

Deployment works fine with default metrics but cannot scrape the Jenkins metrics inside Prometheus/Grafan? 
I am using JCasC for Jenkins deployment and also using "metrics-access-key" inside configuration so that other services can talk to Jenkins such as Prometheus.

 ```
# Definition of the metrics plugin to monitor Jenkins via Prometheus
  metricsaccesskey:
    accessKeys:
      - key: "2a1fcc67-617b-44dc-91d2-4c9d888dac5d"
        description: "Jenkins API token"
        canPing: true
        canThreadDump: false
        canHealthCheck: true
        canMetrics: true
        origins: "*"
```

_Unfortunately, it is not documented in Helm chart documentation where to configure such a key._

**My custom values:** prom-values-int.yaml

```
prometheus:
  enabled: true   
  additionalServiceMonitors: 
    - name: "jenkins-servicemonitor"
      selector: 
        matchLabels:
          app.kubernetes.io/name: '^.*$'
      endpoints: 
        - port: "8080"
          targetPort: "8080"

      ## File containing bearer token to be used when scraping targets
      #   bearerTokenFile: ""

          interval: 30s
          path: /jenkins/prometheus
		  
          # My Jenkins is reachable under
          # Ex. http://10.15.9.54/jenkins
```

The only thing that can be seen is that an empty Jenkins servicemonitor endpoint:

**Command line:**
`kubectl port-forward service/prometheus-kube-prometheus-prometheus 9090
`
**In the browser:**
http://localhost:9090/classic/targets

![image](https://user-images.githubusercontent.com/59603187/115687454-79c0e180-a35a-11eb-9173-971450c5287a.png)

Is there any simple solution or anyone has experienced the same? Thanks
