### ISSUE TITLE
"Configuration as Code Plugin" cannot handle the collectNodeStatus attribute

### ISSUE THREAD

**Issue by con-vissenberg** [jenkinsci/prometheus-plugin#525]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
- Jenkins 2.378.3
- Configuration as Code Plugin 1625.v27444588cc3d
- Prometheus-plugin  2.2.2 
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

Use export function of JCasC.

### Expected Results

```
# Removed all unrelated data
unclassified:
  prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectDiskUsage: true
    collectingMetricsPeriodInSeconds: 120
    collectNodeStatus: false
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false

```

### Actual Results

```
# Removed all unrelated data
unclassified:
  prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectDiskUsage: true
    collectingMetricsPeriodInSeconds: 120
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false

```

### Anything else?

When I add `collectDiskUsage: false` to the YAML file and have JCasC process that file, JCasC crashes with a "unknown attribute" error.
