### ISSUE TITLE
Option to disable per-node metrics

### ISSUE THREAD

**Issue by languitar** [jenkinsci/prometheus-plugin#53]
We are using docker slaves in Jenkins, which get random names. As a consequence, more and more series pile up in the database with names like `jenkins_node_docker_76eb8f041ea67_builds_count`. Would be nice if these metrics could be disabled, or if a label/tag was used instead.

**Comment by LuboVarga** [comment]
Imho labe is must. According [prometheus best practice](https://prometheus.io/docs/practices/naming/) it have to be like:
`jenkins_node_builds_count{nodename="docker_76eb8f041ea67"}...

**Comment by angry-cellophane** [comment]
It's a must unless you have 1M unique labels that doesn't make sense. As a workaround I drop these metrics in scrape config.

**Comment by midnightconman** [comment]
Cardinality is something that must be considered when coming up with naming conventions and best practices for metrics. Prometheus recommends that instance / pod specific information be stored in labels, mostly because it allows easier metric aggregation. With the current naming convention, it would require a complex query to see build counts for multiple slaves (probably a join or regex re-label).

Unfortunately ephemeral pods / containers come at a cost, that cost being label cardinality... but this cost does have a bound, as the labels are stored only for the time period metrics are available.

**Comment by languitar** [comment]
Why was this closed? Is there a solution to this issue?

**Comment by mgomersbach** [comment]
I am hitting this bug as well, and I do get the "general obvious warnings about labels", but with these metric naming it becomes rather useless.
Would it hurt to have this as an _option_?

**Comment by midnightconman** [comment]
I am not sure how you guys have your prometheus setup, but I drop these metrics at scrape time via something like this:

```
    - action: drop
      regex: ^jenkins_node_.+_builds$
      sourceLabels:
      - __name__
    - action: drop
      regex: ^jenkins_node_.+_builds_count$
      sourceLabels:
      - __name__
    - action: drop
      regex: ^label_jenkins_.*$
      sourceLabels:
      - __name__
```

I would recommend doing the same, until we get some traction on this feature / bug request.
