### ISSUE TITLE
Prometheus API return blank page

### ISSUE THREAD

**Issue by JingangLi** [jenkinsci/prometheus-plugin#82]
Hi,

I try to use Prometheus plugin in our jenkins setup. As the whole Jenkins is setup by another team, and I just install Prometheus plugin, so I have limited control on the system.

My prometheus plugin version is 2.0.0, metrics plugin is 4.0.2.2 and my jenkins is Jenkins 2.89.2. And now the prometheus API just return blank page. I think the problem is different with other tickets here. As I try to setup the log with org.jenkinsci.plugins.prometheus. Any thing prints out, so I guess the prometheus plugin doesn't execute.

Do you have some idea I can trouble shooting this problem.

BTW the metrics API works well when I generete Key for access it.

Rgds,
Jingang Li

**Comment by JingangLi** [comment]
Hi @markyjackson-taulia ,

Do you have some guide, I can trouble shooting the problem by myself? I think to know where is the problem which is already very helpful for us.

Many thanks.

Rgds,
Jingang Li

**Comment by markyjackson-taulia** [comment]
Are you able to view the Jenkins logs?

**Comment by JingangLi** [comment]
Hi @markyjackson-taulia ,

Thanks for replying me. I can see the log of Jenkins on general logger. But there isn`t content for Prometheus plugin. 

And I also create log on org.jenkinsci.plugins.prometheus, then no log is collected.
That causes me thought the plugin is executed.

Rgds,
Jingang Li

**Comment by konrad-a** [comment]
I have the same issue. There are no Prometheus entries in my Master logs.
curl -v https://my-jenkins/prometheus/
returns 302 Found

curl -v https://my-jenkins/prometheus
returns 200 OK

If I change my settings to use authentication for the endpoint the curl returns 4xx as expected (so the plugin kind of "works")
The result page is always empty.

I tried upgrading from 1.2.2 to 2.0.0 and the issue is still the same.

BTW: where I can find 1.2.3 and 1.2.4 release binaries?
I cannot see them here:
https://updates.jenkins-ci.org/download/plugins/prometheus/

**Comment by markyjackson-taulia** [comment]
@konrad-a oh that is interesting the binaries are not there. Let me get that figured out with artifactory
Thanks for bringing that up. Can you do me a favor and open a separate issue for that so I can track these individually?

**Comment by markyjackson-taulia** [comment]
Can you both verify that the target is registering in your prometheus server? The target being Jenkins? 
You should see something similar to this:
![image](https://user-images.githubusercontent.com/16655670/51771520-158d1580-209e-11e9-8b1a-55bc09e0fb10.png)

**Comment by markyjackson-taulia** [comment]
Can you both verify that your prometheus is showing the Jenkins target as 1/1 up, like this:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/16655670/51771591-5a18b100-209e-11e9-9254-d0578eaa5249.png">

**Comment by konrada** [comment]
> @konrad-a oh that is interesting the binaries are not there. Let me get that figured out with artifactory
> Thanks for bringing that up. Can you do me a favor and open a separate issue for that so I can track these individually?
Opened  #89

**Comment by guillaumeger** [comment]
We have the same problem:
`bash-4.2$ curl -v localhost:8080/prometheus/
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /prometheus/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Mon, 04 Feb 2019 20:24:30 GMT
< X-Content-Type-Options: nosniff
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Content-Length: 0
< Server: Jetty(9.4.z-SNAPSHOT)
< 
* Connection #0 to host localhost left intact`

and

`bash-4.2$ curl -v localhost:8080/prometheus 
* About to connect() to localhost port 8080 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /prometheus HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 302 Found
< Date: Mon, 04 Feb 2019 20:25:03 GMT
< X-Content-Type-Options: nosniff
< Location: http://localhost:8080/prometheus/
< Content-Length: 0
< Server: Jetty(9.4.z-SNAPSHOT)
< 
* Connection #0 to host localhost left intact`

**Comment by markyjackson-taulia** [comment]
@guillaumeger Where are you running your Jenkins instance? Is it local? Would it be helpful if I setup a time I could help walk you through the setup?

**Comment by guillaumeger** [comment]
@markyjackson-taulia It is running in kubernetes in aws. Im a executing the curl command from within the pod. The manifest looks like this:
```
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: jenkins
  name: jenkinsmaster
  labels:
    app: jenkinsmaster
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkinsmaster
      tier: backend
  template:
    metadata:
      labels:
        app: jenkinsmaster
        tier: backend
    spec:
      containers:
      - name: jenkinsmaster
        image: <redacted>/nuglif/jenkinsmaster:v2.147
        resources:
          requests:
            memory: 2500M
            cpu: 250m
          limits:
            memory: 3500M
            cpu: 500m
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: jenkins-home
          mountPath: "/var/jenkins_home"
        env:
        - name: JAVA_OPTS
          value: "-Dfile.encoding=UTF8 -Xmx2048m -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dhudson.model.DirectoryBrowserSupport.CSP= -Dorg.apache.commons.jelly.tags.fmt.timeZone=America/Montreal -Dpermissive-script-security.enabled=true -Dhudson.plugins.active_directory.ActiveDirectorySecurityRealm.forceLdaps=true"
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkinsmaster

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/proxy-body-size: 20m
    ingress.kubernetes.io/proxy-request-buffering: "off"
    kubernetes.io/ingress.class: nginx
  name: jenkinsmaster
  namespace: jenkins
spec:
  rules:
  - host: jenkins.<redacted>
    http:
      paths:
      - backend:
          serviceName: jenkinsmaster
          servicePort: 8080
        path: /

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkinsmaster
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

---

kind: Service
apiVersion: v1
metadata:
  name: jenkinsmaster
  namespace: jenkins
  labels:
    app: jenkinsmaster
    tier: backend
spec:
  selector:
    app: jenkinsmaster
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: ui
  - protocol: TCP
    port: 50000
    name: jnlp
```
The configuration of the plugin looks like that:
![screen shot 2019-02-05 at 09 23 49](https://user-images.githubusercontent.com/7086664/52279567-d4132a80-2927-11e9-83e6-132d6f2da368.png)

I can successfully see metrics with `https://<jenkins-url>/metrics/currentUser/metrics` but `https://<jenkins-url>/prometheus` returns 200 with an empty page.
